spring:
  application:
    name: ddd
  output:
    ansi:
      enabled: always
  profiles:
    include: >
      db
  datasource:
    ##profile: db
    #url: jdbc:h2:file:./target/db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    #url: jdbc:h2:mem:db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    schema: classpath*:/db/migration/V1__schema.sql
    initialization-mode: embedded
    username: sa
    password: ''
logging:
  level:
    org.springframework.test.context.transaction.TransactionContext: 'off'
    org.springframework.jdbc.core.JdbcTemplate: 'DEBUG'
    #org.springframework.jdbc: 'TRACE'
