spring:
  application:
    name: ddd-layer
  output:
    ansi:
      enabled: always
  profiles:
    include: >
      db
  datasource:
    schema: classpath*:/db/migration/V1__schema.sql
    initialization-mode: embedded
    username: sa
    password: ''
logging:
  level:
    org.springframework.test.context.transaction.TransactionContext: 'off'
    #org.springframework.jdbc.core.JdbcTemplate: 'DEBUG'
